### ISSUE TITLE
JSONDecodeError

### ISSUE THREAD

**Issue by JonW13** [AnthonyBloomer/weather-api#9]
Hi @AnthonyBloomer 
I downloaded the weather api and it worked a few days ago using a jupyter notebook but when I tried to run the code now it gives me a JSONDecodeError.
In the following line:
location = weather.lookup_by_location('dublin')

Can you advise me to do anything?

**Comment by AnthonyBloomer** [comment]
Hi @JonW13, Is there any further information you can provide so I can try replicate this issue?

**Comment by AnthonyBloomer** [comment]
Hi @JonW13,

If you could submit the error report that would be helpful as your code looks fine and I'm not able to replicate this issue here. 

I've updated the weather api to log the JSON response and HTTP status code allowing us to easily identify and report on issues. It would be great if you could update to 1.0.3 by running `pip install --upgrade --force-reinstall weather-api` and report any issues you find.

Thanks,
Anthony

**Comment by AnthonyBloomer** [comment]
According to this article [here](http://www.scrapebox.com/yahoo-999-error): the most common reason for receiving a 999 status code is due to some sort of bandwidth limiting system that Yahoo has put in place on their servers. 

I can't seem to find any rate limiting information on Yahoos documentation so I have not implemented rate limiting mechanism in the package. Have you been making a lot of consecutive requests to the API? Perhaps if you could try another IP to see if that is the reason for being unable to use it.

**Comment by JonW13** [comment]
Thanks, I will try using another IP.
